### ISSUE TITLE
[bug] verschil documentatie en library

### ISSUE THREAD

**Issue by MartenPostma** [Corderius-College-Amersfoort/play#11]
### What happened?

In de documentatie staat:
play.key_is_pressed('d')

in onze refactor staat nu:
play.keypress.key_is_pressed('d')

welke willen we?

### Version

latest

**Comment by beixin555** [comment]
我也遇到了类似问题。
在键盘输入时，由于输入法的原因，会导致出错。
还就是数字小键盘在打开或是关闭的情况下，有时候会导致出错。

**Comment by koen1711** [comment]
Fixed :heavy_check_mark:
