### ISSUE TITLE
Distance functie voor botsingen tussen objecten

### ISSUE THREAD

**Issue by Stellarwastaken** [Corderius-College-Amersfoort/play#12]
### How can we better our software?
Met deze functie kun je de botsingen geleidelijker laten verlopen, omdat de objecten niet met een vierkant eromheen gemeten worden, maar met de werkelijke afstand ertussen. (werkt alleen voor cirkels, omdat het gedaan wordt met de radius sen van cirkels.)

def distance(self, persoon):
     return math.sqrt((self.object.x-persoon.object.x)**2+(self.object.y-persoon.object.y)**2)

**Comment by koen1711** [comment]
This is already a function, called distance_to
