### ISSUE TITLE
[bug] async werkt niet

### ISSUE THREAD

**Issue by Danieldebeste** [Corderius-College-Amersfoort/play#26]
### What happened?

`import play
ball = play.new_circle(
    color="black",
    x=0,
    y=0,
    radius=30
)
ball.start_physics(
    x_speed=30,
    y_speed=10,
    obeys_gravity=False
)
box1 = play.new_box(
    color="black",
    x=-380,
    y=0,
    width=20,
    height=150,)
box2 = play.new_box(
    color="black",
    x=380,
    y=0,
    width=20,
    height=150,)
muur1 = play.new_box(
    x=400,
    y=0,
    width=20,
    height=800,
    transparency=0
)
muur2 = play.new_box(
    x=-400,
    y=0,
    width=20,
    height=800,
    transparency=0
)
score1 = 0
score2 = 0
tekst_links = play.new_text(
    words=str(f"{score1}   I   {score2}"),
    x=0,
    y=200
)
@ball.when_touching(box1)
def botsing1():
    global score1
    ball.physics.x_speed = 30
    score1 +=1
    tekst_links.words = score1
@ball.when_touching(box2)
def botsing2():
    ball.physics.x_speed = -30
@ball.when_touching(muur1)
async def botsing_muur1():
    global score1
    score1 += 1
    print("ballen")
    tekst_links.words=f"{score1}   I   {score2}"
    await play.timer(seconds=3)
    ball.x = 0
    ball.y = 0

@ball.when_touching(muur2)
async def botsing_muur2():
    global score2
    score2 += 1
    print("huh")
    tekst_links.words=f"{score1}   I   {score2}"
    await play.timer(seconds=3)
    ball.x = 0
    ball.y = 0
@play.when_key_pressed("w")
def move_box1_up(key):
    if key == "w":
        if play.screen.top > box1.top:
            box1.y += 5
@play.when_key_pressed("s")
def move_box1_down(key):
    if key == "s":
        if play.screen.bottom < box1.bottom:
            box1.y -= 5
@play.when_key_pressed("up")
def move_box2_up(key):
    if key == "up":
        if play.screen.top > box2.top:
            box2.y += 5
@play.when_key_pressed("down")
def move_box2_down(key):
    if key == "down":
        if play.screen.bottom < box2.bottom:
            box2.y -= 5
play.start_program()
`
ik verwachtte dat ik op deze manier niet meerdere punten zou krijgen als ik de muur raak maar helaas, dat is niet opgelost en hij teleport de bal uiteindelijk naar het midden zonder verder te bewegen. 

### Version

2.1.2 corderius play

**Comment by TJulesL** [comment]
Het probleem komt niet door de async functie, omdat hij je de functie asynchronisch heb gemaakt zal hij elke keer tegelijkertijd **terwijl** de bal de muur aan raakt de functie laten runnen. Dit zorgt ervoor als de bal meerdere frames of "updates" van het programma nog in de muur zit dan zal hij meerdere keren de functie uitvoeren. 

Hij doet wel wat je vraagt, wachten voor 1 seconde maar hij voert dat dus 4x tegelijkertijd uit. Als je niet async zou gebruiken zou je nogsteeds op hetzelfde probleem komen want ookal is de kans kleiner hij is nogsteeds erg groot dat hij meerdere keren de functie achter mekaar uitvoert omdat hij mischien meerdere frames de muur aanraakt. 

Ik zal eventueel later nog kijken of ik een fix kan toevoegen dat hij 1 keer maar kan triggeren totdat de bal / het object de muur weer niet aanraakt. Dat zou uiteraard simpel zijn als het niet was dat er op dat moment dus nog een bal kan komen en dezelfde muur aanraken en omdat de andere bal dan nog de muur aan raakt, kan hij dat niet registeren. Het word dus nog even naar een oplossing zoeken maar ondertussen kan je wel een stuk code maken zoals dit :

```py
import play

timeout_muur1 = False

@ball.when_touching(muur1)
async def botsing_muur1():
    global timeout_muur1
    global score1
    if ball.is_touching(muur1) and timeout_muur1 == False: # kijkt naar de timeout of er niet een ander programma runt in parallel en of hij de muur raakt
        timeout_muur1 = True # zo niet dan zet een timeout zodat de functie niet opnieuw achter elkaar uitgevoerd kan worden totdat de huidige klaar is
        score1 += 1 # verder de normale code
        tekst_links.words=f"{score1} I {score2}" 
        ball.x = 0
        ball.y = 0
        await play.timer(seconds=1) # aan het einde wachten we in deze functie voordat we de timeout weer uit zetten zodat er weer een punt gescoort kan worden
        timeout_muur1 = False
```

Als het goed is zou dit moeten werken (in ieder geval voor 1 muur), Het is even een tijdelijke oplossing voordat er een fix ervoor komt. Hopelijk kan je hier mee verder

**Comment by koen1711** [comment]
This is now really fixed where the when_touching hopefully shouldn't be called twice a frame now.
