### ISSUE TITLE
[question] Release new package?

### ISSUE THREAD

**Issue by TJulesL** [Corderius-College-Amersfoort/play#31]
### How can we better our software?

I had the question if the newly added bug fixes etc. could be released to github (/ pypi.org) as version 2.2.0 since there were some major enhancements / bugs that are fixed now

**Comment by koen1711** [comment]
Sure, I did some testing this evening to maybe fix some bugs and then release. Which I've now completed

**Comment by TJulesL** [comment]
Thank you
