### ISSUE TITLE
[enhancement] play.image needs pygame.image.load instead of strings

### ISSUE THREAD

**Issue by MartenPostma** [Corderius-College-Amersfoort/play#36]
### What happened?

A bug happened!
to change the image, currently this works:

afbeelding = play.new_image('chips.png')
afbeelding.image = pygame.image.load('door.png')

the preferred way would be:
afbeelding = play.new_image('chips.png')
afbeelding.image = 'door.png'

without pygame.image.load

### Version

latest

**Comment by koen1711** [comment]
True! This is not intended behavior, when accessing ._image you're messing with internal code, not with intended behavior for users.
