### ISSUE TITLE
[enhancement] when_touching activates when sprite is hidden

### ISSUE THREAD

**Issue by MartenPostma** [Corderius-College-Amersfoort/play#37]
### What happened?

A bug happened!

`import play

ball = play.new_circle('black',
                       x=0,
                       y=0,
                       radius=30)

ball.start_physics(x_speed=10,
                   obeys_gravity=False)

box = play.new_box(color='black',
                   x=300,
                   y=0,
                   width=30,
                   height=300,
                   border_color="black",
                   border_width=10)

box.hide()

@ball.when_touching(box)
def collision():
    print('dit zou je moeten zien ook al is de box hidden')
    if box.is_hidden == False:
        ball.x=0
        ball.physics.x_speed = ball.physics.x_speed * -1

play.start_program()
`

### Version

latest

**Comment by koen1711** [comment]
True! Although it might be handy to keep this for behaviors like making invisible checkpoints and other features, and more something for the user to think about themselves.
