### ISSUE TITLE
[bug] default font does not seem to exist in most installations

### ISSUE THREAD

**Issue by MartenPostma** [Corderius-College-Amersfoort/play#39]
### What happened?

A bug happened!

`import play

tekst_links = play.new_text(
    words='standaard tekst',  # dit is de tekst aan het begin
    x=0,
    y=0,
    font="arial.ttf",

)

play.start_program()
`

### Version

latest

### Relevant log output

```shell
pygame 2.5.2 (SDL 2.28.3, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
2024-12-04 19:14:14,908 - play - WARNING - File to font doesnt exist, Using default font (text.py:116)
NoneType: None
```

**Comment by koen1711** [comment]
This is intended, although we could change how it works now, but we load `/path/to/font` by default, which doesn't exist so we load the default font.

If you would like to load `YOUR_PROJECT/arial.tff` your code works perfectly fine.

I dont't understand what the bug is.

**Comment by TJulesL** [comment]
@koen1711 @MartenPostma its a small bug in the code which is because it first checks if the file exists and only after that loads the default font. If no font is specified it will always look first for the arial.tff file in the same directory. I will change a fix and make a pull request
