### ISSUE TITLE
[bug] play.new_sound is not playing sound

### ISSUE THREAD

**Issue by MJVDMEEL** [Corderius-College-Amersfoort/play#40]
### What happened?

import play

@play.when_program_starts
def muziek():
    play.new_sound('pongncs.mp3')

    
play.start_program()

I expected pygame to play the .mp3 but it did not play the sound. It seems like it recognized the file but wasn't playing any sound.

### Version

latest

### Relevant log output

```shell
2024-12-05 11:42:00,256 - play - INFO - Loaded sound file (sound.py:32)
NoneType: None``
```

**Comment by koen1711** [comment]
Hi, so to play sound you'll have to assign your sound object to a variable like this:
`sound = play.new_sound('pongncs.mp3')`
And then you should play it like this:
`sound.play()`
